# Generated by Django 5.2.3 on 2025-06-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assigned_to',
        ),
    ]
