# Generated by Django 5.2.3 on 2025-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='task_asset'),
        ),
    ]
