# Generated by Django 5.2.3 on 2025-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/default.jpg', null=True, upload_to='task_asset'),
        ),
    ]
